networks:
  foodorder-network:

volumes:
  postgres_data:
services:
  postgres:
    image: 'postgres:17.6-alpine'
    container_name: foodorder-db
    environment:
      - 'POSTGRES_DB=fooddb'
      - 'POSTGRES_PASSWORD=p@ssw0rd'
      - 'POSTGRES_USER=fooddb'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - foodorder-network

  mailhog:
    image: jcalonso/mailhog:latest
    container_name: foodorder-mailhog
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - foodorder-network